import { Inter, Play, Playfair_Display_SC } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const playfair = Playfair_Display_SC({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'DDustOffCleaning',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={playfair.className}>{children}</body>
    </html>
  );
}
